name: Transfert vers Backblaze B2

on:
  workflow_dispatch: # Permet de lancer le transfert manuellement d'un simple clic

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code de Github
      uses: actions/checkout@v4

    - name: Synchronisation vers Backblaze
      uses: jakejarvis/backblaze-b2-action@master # Version stable corrigée
      env:
        B2_APPKEY_ID: ${{ secrets.B2_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET: ${{ secrets.B2_BUCKET_NAME }}
        SOURCE_DIR: './devoirs_physique_decoupes'
